# -*- coding: utf-8 -*-
{
    "name": "Commercial Demo Story",
    "version": "19.0.1.0.34",
    "category": "Sales",
    "summary": "Presentation dashboard, flashcards, workflow story, and safe demo helpers",
    "description": "Executive navigation and narration for a multi-channel retail demo (B2B, eCommerce, POS, accounting). KPIs are read-only. Reset removes only generated COMM-DEMO story steps, never live transactions.",
    "author": "Horizon Retail Demo",
    "license": "LGPL-3",
    "depends": [
        "base",
        "analytic",
        "sale",
        "account",
        "stock",
        "point_of_sale",
        "pos_sale",
        "pos_hr",
        "pos_restaurant",
        "pos_enterprise",
        "website_sale",
        "hr",
        "account_reports",
        "account_budget",
        "sales_team",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/build_story_views.xml",
        "views/presentation_views.xml",
        "data/build_story.xml",
        "data/demo_presentation.xml",
        "views/crm_team_views.xml",
        "views/demo_dashboard_views.xml",
        "views/demo_flashcard_views.xml",
        "views/demo_story_views.xml",
        "data/demo_dashboard.xml",
        "data/demo_actions.xml",
        "data/demo_pos_filters.xml",
        "data/demo_pos_demo_actions.xml",
        "data/demo_pos_hierarchy_actions.xml",
        "views/pos_config_demo_views.xml",
        "views/pos_demo_search_views.xml",
        "data/demo_scenarios.xml",
        "data/demo_flashcards.xml",
        "data/demo_story_steps.xml",
        "data/demo_analytic_bootstrap.xml",
        "data/demo_database/product_category.xml",
        "data/demo_database/account_analytic_plan.xml",
        "data/demo_database/account_analytic_account.xml",
        "data/demo_database/product_template.xml",
        "data/demo_database/res_partner.xml",
        "data/demo_database/res_partner_category.xml",
        "data/demo_database/res_partner_contact_locations.xml",
        "data/demo_database/res_partner_contacts_full.xml",
        "data/demo_database/crm_team.xml",
        "data/demo_database/crm_team_pos_regions.xml",
        "data/demo_database/demo_bootstrap_transactions.xml",
        "views/menu.xml",
        "views/menu_pos_accounting_prep.xml",
    ],
    "installable": True,
    "application": False,
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
}
